language: cpp
compiler:
  - clang
  - gcc
os:
  - linux
before_install:
  - wget https://cmake.org/files/v3.6/cmake-3.6.3-Linux-x86_64.sh
  - sudo sh cmake-3.6.3-Linux-x86_64.sh --skip-license --prefix=/usr
install:
  - cmake .
script:
  - make .